In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/content/01 covid_toy (1).csv")
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [3]:
print(df.cough.value_counts())

print()
print()

print(df.city.value_counts())

cough
Mild      62
Strong    38
Name: count, dtype: int64


city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [4]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [5]:
x = df.iloc[:,0:5]
y = df.drop(x, axis = 'columns')

print(x.head())

print()
print()
print()

print(y.head())

   age  gender  fever cough     city
0   60    Male  103.0  Mild  Kolkata
1   27    Male  100.0  Mild    Delhi
2   42    Male  101.0  Mild    Delhi
3   31  Female   98.0  Mild  Kolkata
4   65  Female  101.0  Mild   Mumbai



  has_covid
0        No
1       Yes
2        No
3        No
4        No

In [6]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2)
print(x_train.head())
print()
print()
print(y_train.head())

    age  gender  fever   cough     city
68   54  Female  104.0  Strong  Kolkata
10   75  Female    NaN    Mild    Delhi
80   14  Female   99.0    Mild   Mumbai
61   81  Female   98.0  Strong   Mumbai
88    5  Female  100.0    Mild  Kolkata


   has_covid
68        No
10        No
80       Yes
61        No
88        No

In [7]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

In [8]:
si = SimpleImputer()
le = LabelEncoder()

In [10]:
y_train.has_covid = le.fit_transform(y_train.has_covid)
y_test.has_covid = le.transform(y_test['has_covid'])

In [12]:
x_train['fever'] = si.fit_transform(x_train[['fever']])

In [13]:
from sklearn.preprocessing import OrdinalEncoder

In [14]:
oe = OrdinalEncoder()

x_train['cough'] = oe.fit_transform(x_train[['cough']])
x_test['cough'] = oe.transform(x_test[['cough']])

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
ohe = OneHotEncoder(drop='first', sparse_output = False)

In [18]:
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])
x_test_gender_city = ohe.transform(x_test[['gender','city']])

print(x_train_gender_city.shape)
print(x_test_gender_city.shape)

(80, 4)
(20, 4)

In [21]:
from sklearn.compose import ColumnTransformer

In [32]:
transformer = [('trans1',SimpleImputer(),['fever']),
 ('trans2',OrdinalEncoder(categories = [['Mild', 'Strong']]),['cough']),
  ('trans3',OneHotEncoder(sparse_output = False,drop = 'first'),['gender','city'])
  ]

In [35]:
ct = ColumnTransformer(transformers = transformer, remainder = 'passthrough')