In [2]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("/content/00 Social_Network_Ads.csv")
df

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [7]:

# Independent and dependent variables
x = df[['Gender', 'Age', 'EstimatedSalary']]
y = df['Purchased']
x

     Gender  Age  EstimatedSalary
0      Male   19            19000
1      Male   35            20000
2    Female   26            43000
3    Female   27            57000
4      Male   19            76000
..      ...  ...              ...
395  Female   46            41000
396    Male   51            23000
397  Female   50            20000
398    Male   36            33000
399  Female   49            36000

[400 rows x 3 columns]

In [35]:
# Train-test split
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x_encoded, y, test_size=0.2, random_state=1)

x_train

     Age  EstimatedSalary  Gender_Male
93    29            28000        False
23    45            22000        False
299   46           117000         True
13    32            18000         True
90    22            81000         True
..   ...              ...          ...
255   52            90000        False
72    20            23000        False
396   51            23000         True
235   46            79000         True
37    30            49000         True

[320 rows x 3 columns]

In [9]:
# Standardization
from sklearn.preprocessing import StandardScaler

ss = StandardScaler().set_output(transform="pandas")
x_train_scaled = ss.fit_transform(x_train)
x_test_scaled = ss.transform(x_test)

x_train_scaled

          Age  EstimatedSalary  Gender_Male
93  -0.803301        -1.191218         -1.0
23   0.756980        -1.368598         -1.0
299  0.854498         1.439920          1.0
13  -0.510748        -1.486851          1.0
90  -1.485924         0.375639          1.0
..        ...              ...          ...
255  1.439603         0.641709         -1.0
72  -1.680959        -1.339035         -1.0
396  1.342085        -1.339035          1.0
235  0.854498         0.316513          1.0
37  -0.705783        -0.570388          1.0

[320 rows x 3 columns]

In [10]:
x_train.describe()

              Age  EstimatedSalary
count  320.000000       320.000000
mean    37.237500     68293.750000
std     10.270625     33878.650655
min     18.000000     15000.000000
25%     29.000000     43000.000000
50%     37.000000     65000.000000
75%     45.000000     85250.000000
max     60.000000    150000.000000

In [11]:
x_train_scaled.describe()

                Age  EstimatedSalary  Gender_Male
count  3.200000e+02     3.200000e+02   320.000000
mean   2.664535e-16     6.938894e-18     0.000000
std    1.001566e+00     1.001566e+00     1.001566
min   -1.875994e+00    -1.575541e+00    -1.000000
25%   -8.033008e-01    -7.477678e-01    -1.000000
50%   -2.316042e-02    -9.737426e-02     0.000000
75%    7.569800e-01     5.012834e-01     1.000000
max    2.219743e+00     2.415510e+00     1.000000

In [21]:
from sklearn.linear_model import LogisticRegression

In [20]:
lr = LogisticRegression()
lr.scaled = LogisticRegression()

In [30]:
lr.fit(x_train, y_train)       #training with unscaled dataframe

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [31]:
lr.scaled.fit(x_train_scaled, y_train)      #training with scaled dataframe

LogisticRegression()

In [24]:
y_pred_unscaled = lr.predict(x_test)
y_pred_scaled = lr.scaled.predict(x_test_scaled)

In [34]:
#Getting accuracy scored of both scaled and unscaled.

from sklearn.metrics import accuracy_score

accuracy_unscaled = accuracy_score(y_test, y_pred_unscaled)
accuracy_scaled = accuracy_score(y_test, y_pred_scaled)

print(f"Accuracy on unscaled dataframe : {accuracy_unscaled}.\nAccuraacy on scaled dataframe : {accuracy_scaled}")

Accuracy on unscaled dataframe : 0.85.
Accuraacy on scaled dataframe : 0.825